from ._version import __version__ as __version__
from _typeshed import Incomplete

REC_STATUS_CACHE: Incomplete
REC_TYPE_CACHE: Incomplete
DUP_METHOD_CACHE: Incomplete
UTC_OFFSET: Incomplete
LOG: Incomplete

def url_encode(value=None): ...
def create_find_time(time: str = ''): ...
def utc_to_local(utctime: str = '', omityear: bool = False, omitseconds: bool = True): ...
def get_utc_offset(backend=None, opts=None): ...
def rec_status_to_string(backend=None, rec_status: int = 0, opts=None): ...
def rec_type_to_string(backend=None, rec_type: int = 0, opts=None): ...
def dup_method_to_string(backend=None, dup_method: int = 0, opts=None): ...
