from _typeshed import Incomplete


class BEConnection:
    logmodule: str
    connected: bool
    log: Incomplete
    host: Incomplete
    port: Incomplete
    hostname: Incomplete
    deadline: Incomplete
    blockshutdown: Incomplete
    localname: Incomplete
    def __init__(self, backend, port, localname=None, blockshutdown: bool = False, timeout: float = 10.0) -> None: ...
    def __del__(self) -> None: ...
    socket: Incomplete
    def connect(self) -> None: ...
    def disconnect(self, hard: bool = False) -> None: ...
    def reconnect(self, hard: bool = False) -> None: ...
    def announce(self) -> None: ...
    def check_version(self) -> None: ...
    def backendCommand(self, data, deadline=None): ...
    def blockShutdown(self) -> None: ...
    def unblockShutdown(self) -> None: ...
